version: "3"

services:
    client:
        tty: true
        image: docker.io/bitnami/laravel:10
        restart: always
        ports:
            - 3000:3000
        volumes:
            - ./:/app
        entrypoint: [
                "bash",
                "-c",
                "composer install && php artisan key:generate --force && php artisan serve --host=0.0.0.0 --port=3000",
            ]
