helmDefaults:
  wait: true
  waitForJobs: true
  timeout: 1800

releases:
  - name: backend
    namespace: production
    chart: ./backend
    jsonPatches:
    - ./backend/deployment.yaml.gotmpl
    # jsonPatches:
    # - target:
    #     group: apps
    #     version: v1
    #     kind: Deployment
    #     name: "backend"
    #   patch:
    #   - op: replace
    #     path: /spec/template/spec/containers/0/image
    #     value: {{ requiredEnv "IMAGE_VERSION" }}