 apiVersion: networking.k8s.io/v1 # for versions before 1.14 use extensions/v1beta1
 kind: Ingress
 metadata:
   name: backend
 spec:
   ingressingressClassName: nginx
   rules:
  #  - host: backoffice.bilpay.id
  #    http:
  #      paths:
  #      - path: /
  #        backend:
  #          service:
  #           name: backend
  #           port: 
  #             number: 80
  #        pathType: Prefix
   - host: bilpay.id
     http:
       paths:
       - path: /
         backend:
           service:
            name: backend
            port: 
              number: 80
         pathType: Prefix